version: '3.9'

services:
  server:
    restart: on-failure
    image: romanreznikov/hackathon-october-codebattle-backend:0.1.3
    environment:
      - PYTHONUNBUFFERED=1
      - HOC_BUILD_NUMBER=0.1.3
      - HOC_DEBUG=0
      - HOC_ENVIRONMENT=prod
      - HOC_LOG_LEVEL=INFO
      - HOC_PROJECT_NAME=hackathon-codebattle
      - HOC_PROJECT_BASE_URL=http://51.250.36.15
      - HOC_API_V1_STR=/api/v1
      - HOC_API_HEALTHCHECK_PATH=/healthcheck
      - HOC_API_DEFAULT_PAGINATION_LIMIT=10
      - HOC_API_CONFIG_DEPENDENCY_KEY=config
      - HOC_API_REDIS_CLIENT_DEPENDENCY_KEY=redis_client
      - HOC_API_DB_SESSION_DEPENDENCY_KEY=db_session
      - HOC_DB_ECHO=false
      - HOC_DB_ECHO_POOL=false
      - HOC_DB_POOL_DISABLE=false
      - HOC_DB_POOL_MAX_OVERFLOW=10
      - HOC_DB_POOL_SIZE=5
      - HOC_DB_POOL_TIMEOUT=30
      - HOC_DB_HOST=db
      - HOC_DB_PORT=5432
      - HOC_DB_NAME=hackathon-october-codebattle
      - HOC_DB_USER=hackathon
      - HOC_DB_PASSWORD=codebattle
      - HOC_REDIS_HOST=redis
      - HOC_REDIS_PORT=6379
      - HOC_REDIS_DB=0
      - HOC_REDIS_DEFAULT_CHARSET=utf-8
      - HOC_REDIS_DECODE_RESPONSES=1
      - HOC_REDIS_RETRY_ON_TIMEOUT=1
      - HOC_OPENAPI_TITLE=HackathonCodeBattleAPI
      - HOC_OPENAPI_VERSION=0.1.0
      - HOC_OPENAPI_CONTACT_NAME=RomanReznikov
      - HOC_OPENAPI_CONTACT_EMAIL=romanreznikov.am@gmail.com
      - HOC_SERVER_PORT=80
      - HOC_SERVER_NAME=localhost
      - HOC_SERVER_HOSTS=http://51.250.36.15
      - HOC_USE_STUBS=0
      - HOC_TESTING=0
      - HOC_CI=0
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0-alpine
    expose:
      - 6379
    volumes:
      - /mnt/data/redis:/data
    healthcheck:
      test: redis-cli -p 6379 ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14.5-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hackathon
      - POSTGRES_PASSWORD=codebattle
      - POSTGRES_DB=hackathon-october-codebattle
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -d hackathon-october-codebattle -U hackathon
      interval: 5s
      timeout: 5s
      retries: 5

x-yc-disks:
  - device_name: compute-disk-data
    fs_type: ext4
    host_path: /mnt/data/redis
    partition: 1
  - device_name: compute-disk-data
    fs_type: ext4
    host_path: /mnt/data/postgres
    partition: 1
