version: '3.9'

services:
  server:
    restart: on-failure
    image: romanreznikov/hackathon-october-codebattle-backend:latest
    env_file:
      - $ENV
    environment:
      - HOC_BUILD_NUMBER=${HOC_BUILD_NUMBER}
      - HOC_OPENAPI_VERSION=${HOC_OPENAPI_VERSION}
    ports:
      - "${HOC_SERVER_PORT}:${HOC_SERVER_PORT}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0-alpine
    expose:
      - 6379
    volumes:
      - redis_data:/data
    healthcheck:
      test: redis-cli -p 6379 ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14.5-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${HOC_DB_USER}
      - POSTGRES_PASSWORD=${HOC_DB_PASSWORD}
      - POSTGRES_DB=${HOC_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -d $HOC_DB_NAME -U $HOC_DB_USER
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis_data:
  postgres_data:
