version: '3.9'

services:
  server:
    restart: on-failure
    image: romanreznikov/hackathon-october-codebattle-backend:0.1.4
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  redis:
    image: redis:7.0-alpine
    expose:
      - 6379
    volumes:
      - /mnt/data/redis:/data
    healthcheck:
      test: redis-cli -p 6379 ping || exit 1
      interval: 5s
      timeout: 5s
      retries: 5

  db:
    image: postgres:14.5-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=hackathon
      - POSTGRES_PASSWORD=codebattle
      - POSTGRES_DB=hackathon-october-codebattle
    volumes:
      - /mnt/data/postgres:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -d hackathon-october-codebattle -U hackathon
      interval: 5s
      timeout: 5s
      retries: 5

x-yc-disks:
  - device_name: compute-disk-data
    fs_type: ext4
    host_path: /mnt/data/redis
    partition: 1
  - device_name: compute-disk-data
    fs_type: ext4
    host_path: /mnt/data/postgres
    partition: 1
