"""CompanyInitial.

Revision ID: 50510ada9dc4
Revises: 1dcd53d750e9
Create Date: 2022-10-17 12:24:33.241124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "50510ada9dc4"
down_revision = "1dcd53d750e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("summary", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company")
    # ### end Alembic commands ###
