"""CompanyNameIndex.

Revision ID: b29f0be32980
Revises: eda2f487196c
Create Date: 2022-10-17 12:28:50.974542

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "b29f0be32980"
down_revision = "eda2f487196c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_company_name"), "company", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_company_name"), table_name="company")
    # ### end Alembic commands ###
