"""AdvocateCompany.

Revision ID: eda2f487196c
Revises: 50510ada9dc4
Create Date: 2022-10-17 12:24:58.714980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eda2f487196c"
down_revision = "50510ada9dc4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("advocate", sa.Column("company_id", sa.UUID(), nullable=False))
    op.create_index(op.f("ix_advocate_company_id"), "advocate", ["company_id"], unique=False)
    op.create_foreign_key(op.f("fk_advocate_company_id_company"), "advocate", "company", ["company_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_advocate_company_id_company"), "advocate", type_="foreignkey")
    op.drop_index(op.f("ix_advocate_company_id"), table_name="advocate")
    op.drop_column("advocate", "company_id")
    # ### end Alembic commands ###
