name: Main workflow

on:
  push:
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'docs/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Cache dependencies
        id: cache-lint
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.lint.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.lint.txt
      - name: Run linters
        run: make lint

  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:7.0-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      db:
        image: postgres:14.5-alpine
        env:
          POSTGRES_USER: github
          POSTGRES_PASSWORD: ci_pass
          POSTGRES_DB: test_db
        options: >-
          --health-cmd "pg_isready -d test_db -U github"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Cache dependencies
        id: cache-test
        uses: actions/cache@v3
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}-${{ hashFiles('requirements.test.txt') }}
          restore-keys: ${{ env.pythonLocation }}-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt -r requirements/requirements.test.txt
      - name: Run tests
        run: |
          export PYTHONUNBUFFERED=1
          export HOC_BUILD_NUMBER=0.1.0
          export HOC_DEBUG=1
          export HOC_ENVIRONMENT=ci
          export HOC_LOG_LEVEL=INFO
          export HOC_PROJECT_NAME=hackathon-codebattle
          export HOC_PROJECT_BASE_URL=http://api.localhost:8000
          export HOC_API_V1_STR=/api/v1
          export HOC_API_HEALTHCHECK_PATH=/healthcheck
          export HOC_API_DEFAULT_PAGINATION_LIMIT=10
          export HOC_API_CONFIG_DEPENDENCY_KEY=config
          export HOC_API_REDIS_CLIENT_DEPENDENCY_KEY=redis_client
          export HOC_API_DB_SESSION_DEPENDENCY_KEY=db_session
          export HOC_DB_ECHO=false
          export HOC_DB_ECHO_POOL=false
          export HOC_DB_POOL_DISABLE=false
          export HOC_DB_POOL_MAX_OVERFLOW=10
          export HOC_DB_POOL_SIZE=5
          export HOC_DB_POOL_TIMEOUT=30
          export HOC_DB_HOST=localhost
          export HOC_DB_PORT=5432
          export HOC_DB_NAME=test_db
          export HOC_DB_USER=github
          export HOC_DB_PASSWORD=ci_pass
          export HOC_REDIS_HOST=localhost
          export HOC_REDIS_PORT=6379
          export HOC_REDIS_DB=0
          export HOC_REDIS_DEFAULT_CHARSET=utf-8
          export HOC_REDIS_DECODE_RESPONSES=1
          export HOC_REDIS_RETRY_ON_TIMEOUT=1
          export HOC_OPENAPI_TITLE="Hackathon CodeBattle API"
          export HOC_OPENAPI_VERSION=0.1.0
          export HOC_OPENAPI_CONTACT_NAME="Full Name"
          export HOC_OPENAPI_CONTACT_EMAIL=full.name@gmail.com
          export HOC_SERVER_PORT=8000
          export HOC_SERVER_NAME=localhost
          export HOC_SERVER_HOSTS=http://api.localhost:8000
          export HOC_USE_STUBS=1
          export HOC_TESTING=1
          export HOC_CI=1
          export PYTEST_ADDOPTS="--ignore-glob=tests/functional/*"
          make test

  build-and-push-image:
    needs: [ lint, test ]
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: .
            dockerfile: ./dev.Dockerfile
            image: romanreznikov/hackathon-october-codebattle-backend-dev
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}, ${{ matrix.image }}:latest
          labels: ${{ steps.meta.outputs.labels }}
